### ISSUE TITLE
회의 및 결정

### ISSUE THREAD

**Issue by taggon** [nodejs/nodejs-ko#9]
#3 과 관련있습니다.

다 함께 논의하고 결정해야 할 사항이 있을 때...
1. 회의를 위한 통신 수단은 무엇을 사용하고
2. 안건 채택을 위한 정족수는 몇 명으로 두어야 하는지

**Comment by xarus01** [comment]
1.
기본적으로 Github issue 시스템을 이용하되 즉각적인 수단이 하나 더 필요할 것 같습니다.
Mikeal이 언급한대로 (회의 영상이 Youtube 에 올라가는것이 괜찮으시다면) google hangout도 좋을 것 같습니다.
2. 참여 인원의 과반수로 정하면 어떨까요?

**Comment by jung-kim** [comment]
안녕하새요, @mikeal이 google hangout 를 언급하셧지만 그것의 가장큰 문재는 5명이상이 참여 하지를 못합니다. 지금팀 이 딱 5명 이여서 괜잔을 지만 나중에 더 크면 얼굴을 못보지만은 skype 이 더 쉬울지도 모릅니다.  그래서 방송않하는 회의는 skype 이 더쉬울것입니다.

(13 년동한 한국글 않쓰다가 쓰니까 너무 어숙하내요...  크개 문재가 않된다면은 가끔와서 한국글쓰기 연습하는것을 이해해주시기 바랍니다...  ㅜ.ㅜ)

Hello, @mikeal did mentioned google hangout but the biggest problem is that more then 5 people cannot join.  Right now there is 5 people in the team so it will be fine but skype might be easier even though you don't get to see the faces.  If the meeting will not be broadcasted, skye might be easier.

(it has been 13 years since I have written kreoan so it very akward...  I hope you guys can understand me practicing writing korean here every now and then.

**Comment by taggon** [comment]
실시간 채팅 서비스에 대해서만 동의한다면 굳이 hangout이 아니더라도 slack, gitter같은 대안도 있습니다.
[Gitter](https://gitter.im/) 서비스 소개를 읽어보니 GitHub과 연동이 잘 되는 것 같은데 Gitter를 시도해보는 건 어떨까요? :)

**Comment by outsideris** [comment]
@codingtwinky 행아웃은 최대 10명까지 아닌가요? 화상채팅하는게 좋다는 의견은 아닌데 [io.js TC미팅](https://www.youtube.com/watch?v=OUoWlIshY9s)봐도 8명정도 참여하고 있습니다.

**Comment by outsideris** [comment]
기록상 저는 이슈를 더 선호하긴 하지만 초반이고 해서 협의 필요한 내용이 있다면 저는 slack이나 gitter를 더 선호합니다.
커뮤니케이션의 자유로운 참여를 생각하면 gitter가 더 자연스럽다고 생각합니다.(앱도 있고 채팅에는 부족함은 없습니다.)

**Comment by nundefined** [comment]
저는 특별히 선호하는 것이 없는 상태이긴 합니다만
gitter를 써보지 않아서 gitter를 써봤으면 하는 생각입니다. :)
사용하다가 불편하면 바꾸면 되지 않을까요?

**Comment by taggon** [comment]
주신 의견에 따라 Gitter 채팅룸을 만들었습니다.
GitHub 계정있으니까 로그인 + 두 번 정도 클릭만 하면 끝나는군요. ㄷㄷㄷ
https://github.com/iojs/iojs-kr 에서 join chat 버튼을 클릭하면 됩니다.

**Comment by jung-kim** [comment]
[행아웃](https://support.google.com/plus/answer/1216376?hl=en) 최대 10명 이 맛습니다.  재가 잘못 기억을 잘못했습니다...

**Comment by taggon** [comment]
제가 열었던 이슈를 클로징 할 수는 있군요. ㅎㅎ
통신 수단은 상시 gitter를 사용하는 걸로, 정족수는 과반으로 하겠습니다.
